export const DIET = [
    { name: "---", value: "", id: 0 },
    { name: "balanced", value: "balanced", id: 1 },
    { name: "high-fiber", value: "high-fiber", id: 2 },
    { name: "high-protein", value: "high-protein", id: 3 },
    { name: "low-carb", value: "low-carb", id: 4 },
    { name: "low-fat", value: "low-fat", id: 5 },
    { name: "low-sodium", value: "low-sodium", id: 6 },
];

export const HEALTH = [
    { name: "---", value: "", id: 7 },
    { name: "alcohol-cocktail", value: "alcohol-cocktail", id: 8 },
    { name: "alcohol-free", value: "alcohol-free", id: 9 },
    { name: "celery-free", value: "celery-free", id: 10 },
    { name: "crustacean-free", value: "crustacean-free", id: 11 },
    { name: "dairy-free", value: "dairy-free", id: 12 },
    { name: "DASH", value: "DASH", id: 13 },
    { name: "egg-free", value: "egg-free", id: 14 },
    { name: "fish-free", value: "fish-free", id: 15 },
    { name: "fodmap-free", value: "fodmap-free", id: 16 },
    { name: "gluten-free", value: "gluten-free", id: 17 },
    { name: "immuno-supportive", value: "immuno-supportive", id: 18 },
    { name: "keto-friendly", value: "keto-friendly", id: 19 },
    { name: "kidney-friendly", value: "kidney-friendly", id: 20 },
    { name: "kosher", value: "kosher", id: 21 },
    { name: "low-fat-abs", value: "low-fat-abs", id: 22 },
    { name: "low-potassium", value: "low-potassium", id: 23 },
    { name: "low-sugar", value: "low-sugar", id: 24 },
    { name: "lupine-free", value: "lupine-free", id: 25 },
    { name: "Mediterranean", value: "Mediterranean", id: 26 },
    { name: "mollusk-free", value: "mollusk-free", id: 27 },
    { name: "mustard-free", value: "mustard-free", id: 28 },
    { name: "no-oil-added", value: "no-oil-added", id: 29 },
    { name: "paleo", value: "paleo", id: 30 },
    { name: "peanut-free", value: "peanut-free", id: 31 },
    { name: "pescatarian", value: "pescatarian", id: 32 },
    { name: "pork-free", value: "pork-free", id: 33 },
    { name: "red-meat-free", value: "red-meat-free", id: 34 },
    { name: "sesame-free", value: "sesame-free", id: 35 },
    { name: "shellfish-free", value: "shellfish-free", id: 36 },
    { name: "soy-free", value: "soy-free", id: 37 },
    { name: "sugar-conscious", value: "sugar-conscious", id: 38 },
    { name: "sulfite-free", value: "sulfite-free", id: 39 },
    { name: "dairy-free", value: "dairy-free", id: 40 },
    { name: "tree-nut-free", value: "tree-nut-free", id: 41 },
    { name: "vegan", value: "vegan", id: 42 },
    { name: "vegetarian", value: "vegetarian", id: 43 },
    { name: "wheat-free", value: "wheat-free", id: 44 },

];

export const MEALTYPE = [
    { name: "---", value: "", id: 45 },
    { name: "Breakfast", value: "Breakfast", id: 46 },
    { name: "Dinner", value: "Dinner", id: 47 },
    { name: "Lunch", value: "Lunch", id: 48 },
    { name: "Snack", value: "Snack", id: 49 },
    { name: "Teatime", value: "Teatime", id: 50 },
];

export const DISHTYPE = [
    { name: "---", value: "", id: 51 },
    { name: "Biscuits and cookies", value: "Biscuits and cookies", id: 52 },
    { name: "Bread", value: "Bread", id: 53 },
    { name: "Cereals", value: "Cereals", id: 54 },
    { name: "Condiments and sauces", value: "Condiments and sauces", id: 55 },
    { name: "Desserts", value: "Desserts", id: 56 },
    { name: "Drinks", value: "Drinks", id: 57 },
    { name: "Main course", value: "Main course", id: 58 },
    { name: "Pancake", value: "Pancake", id: 59 },
    { name: "Preps", value: "Preps", id: 60 },
    { name: "Preserv", value: "Preserv", id: 61 },
    { name: "Salad", value: "Salad", id: 62 },
    { name: "Sandwiches", value: "Sandwiches", id: 63 },
    { name: "Side dish", value: "Side dish", id: 64 },
    { name: "Soup", value: "Soup", id: 65 },
    { name: "Starter", value: "Starter", id: 66 },
    { name: "Sweets", value: "Sweets", id: 67 },

];

export const COOKINGTIME = [
    { name: "---", value: "", id: 68 },
    { name: "15 minutes", value: "15", id: 69 },
    { name: "30 minutes", value: "30", id: 70 },
    { name: "1 hour", value: "60", id: 71 },
    { name: "2 hour", value: "120", id: 72 },
];