export const DIET = [
    { name: "---", value: "" },
    { name: "balanced", value: "balanced" },
    { name: "high-fiber", value: "high-fiber" },
    { name: "high-protein", value: "high-protein" },
    { name: "low-carb", value: "low-carb" },
    { name: "low-fat", value: "low-fat" },
    { name: "low-sodium", value: "low-sodium" },
];

export const HEALTH = [
    { name: "---", value: "" },
    { name: "alcohol-cocktail", value: "alcohol-cocktail" },
    { name: "alcohol-free", value: "alcohol-free" },
    { name: "celery-free", value: "celery-free" },
    { name: "crustacean-free", value: "crustacean-free" },
    { name: "dairy-free", value: "dairy-free" },
    { name: "DASH", value: "DASH" },
    { name: "egg-free", value: "egg-free" },
    { name: "fish-free", value: "fish-free" },
    { name: "fodmap-free", value: "fodmap-free" },
    { name: "gluten-free", value: "gluten-free" },
    { name: "immuno-supportive", value: "immuno-supportive" },
    { name: "keto-friendly", value: "keto-friendly" },
    { name: "kidney-friendly", value: "kidney-friendly" },
    { name: "kosher", value: "kosher" },
    { name: "low-fat-abs", value: "low-fat-abs" },
    { name: "low-potassium", value: "low-potassium" },
    { name: "low-sugar", value: "low-sugar" },
    { name: "lupine-free", value: "lupine-free" },
    { name: "Mediterranean", value: "Mediterranean" },
    { name: "mollusk-free", value: "mollusk-free" },
    { name: "mustard-free", value: "mustard-free" },
    { name: "no-oil-added", value: "no-oil-added" },
    { name: "paleo", value: "paleo" },
    { name: "peanut-free", value: "peanut-free" },
    { name: "pescatarian", value: "pescatarian" },
    { name: "pork-free", value: "pork-free" },
    { name: "red-meat-free", value: "red-meat-free" },
    { name: "sesame-free", value: "sesame-free" },
    { name: "shellfish-free", value: "shellfish-free" },
    { name: "soy-free", value: "soy-free" },
    { name: "sugar-conscious", value: "sugar-conscious" },
    { name: "sulfite-free", value: "sulfite-free" },
    { name: "dairy-free", value: "dairy-free" },
    { name: "tree-nut-free", value: "tree-nut-free" },
    { name: "vegan", value: "vegan" },
    { name: "vegetarian", value: "vegetarian" },
    { name: "wheat-free", value: "wheat-free" },

];

export const MEALTYPE = [
    { name: "---", value: "" },
    { name: "Breakfast", value: "Breakfast" },
    { name: "Dinner", value: "Dinner" },
    { name: "Lunch", value: "Lunch" },
    { name: "Snack", value: "Snack" },
    { name: "Teatime", value: "Teatime" },
];

export const DISHTYPE = [
    { name: "---", value: "" },
    { name: "Biscuits and cookies", value: "Biscuits and cookies" },
    { name: "Bread", value: "Bread" },
    { name: "Cereals", value: "Cereals" },
    { name: "Condiments and sauces", value: "Condiments and sauces" },
    { name: "Desserts", value: "Desserts" },
    { name: "Drinks", value: "Drinks" },
    { name: "Main course", value: "Main course" },
    { name: "Pancake", value: "Pancake" },
    { name: "Preps", value: "Preps" },
    { name: "Preserv", value: "Preserv" },
    { name: "Salad", value: "Salad" },
    { name: "Sandwiches", value: "Sandwiches" },
    { name: "Side dish", value: "Side dish" },
    { name: "Soup", value: "Soup" },
    { name: "Starter", value: "Starter" },
    { name: "Sweets", value: "Sweets" },
    
];

export const COOKINGTIME = [
    { name: "---", value: "" },
    { name: "15 minutes", value: "15" },
    { name: "30 minutes", value: "30" },
    { name: "1 hour", value: "60" },
    { name: "2 hour", value: "120" },
];